#!/usr/bin/env sh

sudo dnf copr enable atim/i3blocks -y
sudo dnf install -y i3blocks
sudo dnf install -y calcurse

pip3 install pulsemixer --user

mkdir -p $HOME/.config/i3blocks
ln -sf $BASEPATH/i3blocks-config $HOME/.config/i3blocks/config

mkdir -p $HOME/.config/calcurse
ln -sf $BASEPATH/calcurse-conf $HOME/.config/calcurse/conf
ln -sf $BASEPATH/calcurse-keys $HOME/.config/calcurse/keys

mkdir -p $HOME/.local/bin
ln -sf $BASEPATH/bin/statusbar $HOME/.local/bin/statusbar

