#!/usr/bin/env sh

sudo dnf copr enable atim/i3blocks -y
sudo dnf install -y i3blocks

mkdir -p $HOME/.config/i3blocks
ln -sf $BASEPATH/i3blocks-config $HOME/.config/i3blocks/config

mkdir -p $HOME/.local/bin
ln -sf $BASEPATH/bin/statusbar $HOME/.local/bin/statusbar

